### ISSUE TITLE
PR Request for App

### ISSUE THREAD

**Issue by shra1dhar** [KateDK/react-todo-app#1]
Hey there,
Need to make a PR to any open source project on Github and I stumbled on yours. Can spin up somehting and send you a PR request. Do you have anything specific in mind (feature/enhancement) which you might require as part of the PR?

**Comment by KateDK** [comment]
Hi Shravan,

I did not plan to collaborate on this specific project with anyone.
If you want we can collaborate on a new project together. I can set it up
if you need the project to be created by someone else.

If you only want to add one PR to an open source project I recommend you
check this one out:
https://github.com/NehemiahK/fun-react-lib/tree/master
It was created specifically for people who want to contribute to an open
source project but feel a bit overwhelmed or dont know where to begin.
Check out the readme to understand how it works. :)

Have a great rest of the week!

**Comment by shra1dhar** [comment]
I wanted to do a quick PR as part of Hackoctober challenge. Thanks for that link, I'll look it up :+1:
